#!/bin/bash

# Project structure overview

echo "📁 Ripplica Web Query Application Structure"
echo "=========================================="
echo ""
echo "🗂️  Project Root"
echo "├── 🔧 Backend (FastAPI)"
echo "│   ├── app/"
echo "│   │   ├── api/           # REST API endpoints"
echo "│   │   ├── models/        # Pydantic schemas"
echo "│   │   ├── services/      # Business logic"
echo "│   │   ├── config.py      # Configuration"
echo "│   │   └── main.py        # FastAPI application"
echo "│   ├── requirements.txt   # Python dependencies"
echo "│   ├── run.py            # Server startup"
echo "│   ├── Dockerfile        # Container build"
echo "│   └── .env              # Environment variables"
echo "│"
echo "├── 🎨 Frontend (React + Vite)"
echo "│   ├── src/"
echo "│   │   ├── services/     # API client"
echo "│   │   ├── App.tsx       # Main component"
echo "│   │   └── ...           # Other components"
echo "│   ├── package.json      # Node dependencies"
echo "│   ├── Dockerfile        # Container build"
echo "│   └── .env              # Environment variables"
echo "│"
echo "├── 💾 Data (Shared)"
echo "│   ├── query_cache.faiss # FAISS vector index"
echo "│   └── query_metadata.json # Cache metadata"
echo "│"
echo "└── 🚀 Scripts"
echo "    ├── start.sh          # Full application startup"
echo "    ├── start-backend.sh  # Backend only"
echo "    └── start-frontend.sh # Frontend only"
echo ""
echo "🔗 URLs (when running):"
echo "  Frontend:  http://localhost:5173"
echo "  Backend:   http://localhost:8000"
echo "  API Docs:  http://localhost:8000/docs"
echo ""
echo "🚀 Quick Start:"
echo "  ./start.sh              # Start everything"
echo "  ./start-backend.sh      # Backend only"
echo "  ./start-frontend.sh     # Frontend only"
echo ""
